### ISSUE TITLE
downsample?_loop doesn't support tuple 

### ISSUE THREAD

**Issue by johnnychen94** [JeffFessler/MIRT.jl#49]
It's a better practice in Julia to represent sizes or parameters as tuple instead of vector/array because 1) Tuple is static and immutable 2) Julia has a lot of optimization on Tuple to reduce its overhead.

For this reason, it's better to change the type annotation of `down` to `Tuple` or `NTuple{3, Integer}`, and give a deprecation for `AbstractVector`:

https://github.com/JeffFessler/MIRT.jl/blob/abb2fff4ca432ee08659a5190590968cd6e8a7ac/src/utility/downsample.jl#L100-L104

If you still plan to support AbstractVector, then it could be `Union{Tuple, AbstractVector{<:Integer}}` in this case. BTW, it's not generic to write `AbstractVector{Int}`, it should be `AbstractVector{<:Integer}`

I just accidentally run into this case when setting up benchmark CI, there might be many others in MIRT.

**Comment by JeffFessler** [comment]
Thanks - I've fixed it and in related places.
There are probably more and I'll look out for them going forward.
