### ISSUE TITLE
Hi, could you release some codes?

### ISSUE THREAD

**Issue by ruizhihou** [JeffFessler/MIRT.jl#77]
Hi, Mr. Fessler. It's my great honor to read your papers.

I'm doing some similar works that separate magnitude and phase to reconstruct the MR image. Could you please release the code of your papers as following? Or where can I find the codes?

Thanks!

Papers:

1. Iterative Image Reconstruction in MRI With Separate Magnitude and Phase Regularization

2. Separate Magnitude and Phase Regularization via Compressed Sensing

**Comment by JeffFessler** [comment]
@ruizhihou the MIRT.jl README has a link to my "reproducible research" web page and there you will find links to the code and data for this paper:
Feng Zhao, Douglas Noll, Jon-Frederick Nielsen, J A Fessler.
Separate magnitude and phase regularization via compressed sensing.
IEEE Trans. Med. Imag., 31(9):1713-23, Sep. 2012.

Please look at that code first and then ask me by email if you think you need code for the 2004 ISBI paper.
I think the 2012 paper probably is what you want.
