### ISSUE TITLE
bug in the Julia

### ISSUE THREAD

**Issue by kangpyo** [JeffFessler/MIRT.jl#78]
it shows a bug during executing the code.  

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 --  at 0x1d3e7280 -- OLATION with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 --  at 0x1d3e7280 -- OLATION with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 -- unknown function (ip: 000000001D3E7280)
 reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 -- unknown function (ip: 000000001D3E7280)
 reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION0001D3E7280)
 reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 -- unknown function (ip: 000000001D3E7280)
 reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 -- unknown function (ip: 0000 at 0x1d3e7280 -- unknown function (ip: 000000001D3E7280)
in expression starting at C:\Users\kangpin expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\EXCEPTION_ACCESS_VIOLATION at 0x1d3e7280 -- unknown function (ip: 000000001D3E7280)
in expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
in expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
in expression starting at C:\Users\kangpin expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
in expression starting at C:\Users\kangpin expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
in expression starting at C:\Users\kangpin expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
in expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115
dcabs164_ at C:\Users\kangpyo\AppData\Local\JuliaPro-1.5.2-1\Julia-1.5.2\bin\libopenblas64_.DLL (unknown line)
in expression starting at C:\Users\kangpyo\Dropbox (MIT)\data- MIT\Machine learning\super resolution\MIRT.jl-master_julia\mirt-demo-master\isbi-19\01-recon.jl:115

**Comment by JeffFessler** [comment]
Thanks for your interest in MIRT.
I just installed Julia 1.5.3 on a linux server and added the tagged version of MIRT to it (v0.13.0) and ran the tests an everything passed.  I have not run any tests on a PC myself, but the unit tests in the cloud test windows.
If you want help you need to describe clearly what you were running.

**Comment by JeffFessler** [comment]
no reply so closing issue.  reopen if you need help.

**Comment by kangpyo** [comment]
> no reply so closing issue. reopen if you need help.

sorry for the late reply. I'm actually installing Linux in my office now. I will give you feedback in case I still have the same problem. 
thank you for your follow up.
