### ISSUE TITLE
reconstruction of my own image

### ISSUE THREAD

**Issue by kangpyo** [JeffFessler/MIRT.jl#81]
Hi Prof. Fessler, 

I'm trying to implement MIRT image reconstruction into my electron transmission microscopy (TEM), which often resulted in poor resolution. 
I have been multiple trials in windows but it shows an error and I switched to Linux and it works well with your demonstration. 
now, I'm trying to implement my TEM image in your algorithm "01-recon.jl".
I convert the image RGB to gray and again convert Gray to Float32. 
The code jim seems to recognize the image but fft cannot process the image. 
I believe this is not a major problem but I cannot resolve it. 

here is the error message. 
 ytrue = fft(Xtrue)[samp]
ERROR: BoundsError: attempt to access 1000×1000 Array{Complex{Float32},2} at index [Bool[1 1 … 1 1; 1 1 … 1 1; … ; 1 1 … 1 1; 1 1 … 1 1]]
Stacktrace:
 [1] throw_boundserror(::Array{Complex{Float32},2}, ::Tuple{Base.LogicalIndex{Int64,BitArray{2}}}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] _getindex at ./multidimensional.jl:742 [inlined]
 [4] getindex(::Array{Complex{Float32},2}, ::BitArray{2}) at ./abstractarray.jl:1060
 [5] top-level scope at none:1

could you help me with what I can do next?
once this works, I will implement my videos. I have ~TB of a huge data set of electron microscopy images and video. 
 
Thank you
best
KP

**Comment by JeffFessler** [comment]
Your `samp` array probably has a different size than your `Xtrue` array.
It is better to do this by email than by github issues.  My email is easy to find online so check your array sizes and followup with email if needed.  I will close this issue here because it doesn't look like a MIRT bug.
